VSPHERE_SERVER: <VCENTER IP>
VSPHERE_USERNAME: <VCENTER USERNAME>
VSPHERE_PASSWORD: <VCENTER PASSWORD>
VSPHERE_DATACENTER: /<VCENTER DATACENTER NAME>
VSPHERE_DATASTORE: /<VCENTER DATACENTER NAME>/datastore/<DATASTORE NAME>
VSPHERE_NETWORK: VM Network
VSPHERE_RESOURCE_POOL: /<VCENTER DATACENTER NAME>/host/<CLUSTER NAME>/Resources/<RESOURCE POOL>
VSPHERE_FOLDER: /<VCENTER DATACENTER NAME>/vm/TKG
VSPHERE_TEMPLATE: /<VCENTER DATACENTER NAME>/vm/TKG2/<TKG OVA>
VSPHERE_HAPROXY_TEMPLATE: /<VCENTER DATACENTER NAME>/vm/TKG2/<PROXY OVA>
VSPHERE_DISK_GIB: "20"
VSPHERE_NUM_CPUS: "2"
VSPHERE_MEM_MIB: "2048"
VSPHERE_SSH_AUTHORIZED_KEY: <JUMPBOX SSH KEY>
SERVICE_CIDR: 100.64.0.0/13
CLUSTER_CIDR: 100.64.0.0/13
